### ISSUE TITLE
Spot Requests - "Status: Error"

### ISSUE THREAD

**Issue by mcrosson** [JamesSWiggins/EthMiningCFN#2]
I'm receiving the attached 'error'. Does this mean that the spot fleet can't be deployed due to market conditions or is there possibly something else going on?

Ohio Region

Target # GPUs: 1
Rate: 0.2

![error screenshot](https://user-images.githubusercontent.com/2058383/31143465-709e3250-a84b-11e7-9eba-10f18a8c4d60.png)

**Comment by GiovanniFrigo** [comment]
Have you tried raising your target price per GPU? Worked for me.

**Comment by mcrosson** [comment]
I just wanted to be sure raising the price was the likely cause. Thank you for the feedback.
